name: Bug Report
description: Report a bug or unexpected behavior
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please fill out the information below to help us investigate.

  - type: input
    id: version
    attributes:
      label: Version
      description: What version are you using?
      placeholder: e.g., 1.0.0, commit hash, or "latest"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of the bug
      placeholder: What happened? What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce the issue?
      placeholder: |
        1. Send document to API...
        2. Convert with options...
        3. Observe error...
    validations:
      required: true

  - type: textarea
    id: sample
    attributes:
      label: Sample Document
      description: If applicable, provide a minimal sample document that reproduces the issue
      placeholder: Paste document content, link to file, or describe the document structure

  - type: textarea
    id: logs
    attributes:
      label: Error Output / Logs
      description: Any error messages or relevant log output
      render: shell

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Any relevant environment details
      placeholder: |
        - OS: Ubuntu 22.04
        - Elixir: 1.16
        - Erlang: 26.0
